### ISSUE TITLE
loader-method method executed several times no matter loader-throttle set how large. 

### ISSUE THREAD

**Issue by kid1412621** [molvqingtai/vue-scroll-loader#3]
Tried out better scroll, vue-infinity-scroll, blablabla other tons of vue scroll laod components.
This is absolutely most minimal and practically useful one for both PC and mobile. Thanks for your work.

But as I mentioned in the title, it seems there is a bug.
And if support pull-down-refresh would be awesome.

**Comment by molvqingtai** [comment]
Now 2.0.0 has been refactored using the IntersectionObserver API, which can solve the problem of repeated execution
