### ISSUE TITLE
getting error on destroying component

### ISSUE THREAD

**Issue by 8005736** [molvqingtai/vue-scroll-loader#4]
Error in beforeDestroy hook: "TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'."

I have several columns on page, scroll-loader in each column. When i update key on columns, i catch this error.

**Comment by toanhuynh345** [comment]
I have the same issue. i'm expecting the solutions

**Comment by toanhuynh345** [comment]
I got this error when i redirect another page.
Somdays, i went to core this package and then i figured out this solution:
In beforeDesstroy() you use:
`IntersectionObserver.prototype.unobserve = function (target) { 
                return null;
            };
`
Btw, this solved will not be properly but it could be running.

**Comment by imshadowz** [comment]
I have this issue too.
My Solution for now is. I chang value of props 'loader-disable' to 'false' before page redirect.

**Comment by molvqingtai** [comment]
> Error in beforeDestroy hook: "TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'."
> 
> I have several columns on page, scroll-loader in each column. When i update key on columns, i catch this error.

Thank you for your issue, but I cannot reproduce this error. Can you provide an example of the error?

**Comment by 8005736** [comment]
> Thank you for your issue, but I cannot reproduce this error. Can you provide an example of the error?

<template>
	<div>
		<div class="card-scene">
			<div class="row" v-for="column in columns" :key="column.id">
				<div class="card card-column-header">
					<div class="card-body p-2 user-cards">
						<scroll-loader :loader-method="e => getMore(column.id)" :loader-disable="isDisabled[column.id]"> </scroll-loader>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

When component is destroyed - i catch errors

**Comment by molvqingtai** [comment]
> > Thank you for your issue, but I cannot reproduce this error. Can you provide an example of the error?
> 
> ```
> <div>
> 	<div class="card-scene">
> 		<div class="row" v-for="column in columns" :key="column.id">
> 			<div class="card card-column-header">
> 				<div class="card-body p-2 user-cards">
> 					<scroll-loader :loader-method="e => getMore(column.id)" :loader-disable="isDisabled[column.id]"> </scroll-loader>
> 				</div>
> 			</div>
> 		</div>
> 	</div>
> </div>
> ```
> 
> When component is destroyed - i catch errors

I tried to reproduce this error using your code and it seems that no errors were found
https://codesandbox.io/s/vue-scroll-loader-9ikje

**Comment by brolnickij** [comment]
@molvqingtai hello! thank you for your library!
It seems the people above just forgot to clarify that this problem occurs in SSR (Nuxt.js).

**Comment by molvqingtai** [comment]
It is a pity that SSR is not supported in this library. The temporary solution is to put the core of this library https://github.com/molvqingtai/vue-scroll-loader/tree/master/src/components/Scroll-Loader.vue Copy to your project, remove all life cycles, and replace with created()

**Comment by molvqingtai** [comment]
> I have this issue too.
> My Solution for now is. I chang value of props 'loader-disable' to 'false' before page redirect.

It is a pity that SSR is not supported in this library. The temporary solution is to put the core of this library https://github.com/molvqingtai/vue-scroll-loader/tree/master/src/components/Scroll-Loader.vue Copy to your project, remove all life cycles, and replace with created()

**Comment by molvqingtai** [comment]
> @molvqingtai hello! thank you for your library!
> It seems the people above just forgot to clarify that this problem occurs in SSR (Nuxt.js).
> 
> I now faced exactly the same problem. Can you solve it or can I help you with this? Thanks!

It is a pity that SSR is not supported in this library. The temporary solution is to put the core of this library https://github.com/molvqingtai/vue-scroll-loader/tree/master/src/components/Scroll-Loader.vue Copy to your project, remove all life cycles, and replace with created()

**Comment by molvqingtai** [comment]
@8005736 @toanhuynh345 @imshadowz @brolnickij Thanks everyone, the problem should be fixed now

**Comment by VictorPullzz** [comment]
@molvqingtai Hello, I got this error too 
![image](https://user-images.githubusercontent.com/23406402/77397887-82419400-6db7-11ea-98ad-84d76531e5a6.png)

It happens to me when the parent component, (where it finds vue-scroll-loader), disappears, (v-if use), and during the destruction of the component this error appears...

**Comment by molvqingtai** [comment]
> @molvqingtai您好，我也收到此错误
> ![图片](https://user-images.githubusercontent.com/23406402/77397887-82419400-6db7-11ea-98ad-84d76531e5a6.png)
> 
> 当父组件（在其中找到vue-scroll-loader的组件）消失（（如果使用v）），并且在组件销毁期间出现此错误时，
> 我会发生这种情况... 我想也许是在插件中使用了ref而不是（this。$ el）
> ![图片](https://user-images.githubusercontent.com/23406402/77398157-072cad80-6db8-11ea-9444-4540194ea3fe.png)？

什么版本？
它是否在SSR中运行？
如果有错误的例子，那就更好了，谢谢。

**Comment by molvqingtai** [comment]
> @molvqingtai Hello, I got this error too
> ![image](https://user-images.githubusercontent.com/23406402/77397887-82419400-6db7-11ea-98ad-84d76531e5a6.png)
> 
> It happens to me when the parent component, (where it finds vue-scroll-loader), disappears, (v-if use), and during the destruction of the component this error appears...
> I think maybe in the plugin use ref instead of (this.$el)
> ![image](https://user-images.githubusercontent.com/23406402/77398157-072cad80-6db8-11ea-9444-4540194ea3fe.png) ?

What is the version?
Does it run in SSR?
It would be better if there were wrong examples, thanks.

**Comment by 8005736** [comment]
Fixed, thanks.

**Comment by VictorPullzz** [comment]
@molvqingtai 
1. Last version
2. No is SPA

This problem occurs when using a modal window (something like this: https://element.eleme.io/#/en-US/component/drawer). When I put your plugin on it, it works and there are no problems, but when I close this modal window ,plugin show this error. 
I think (may be) this is due to the fact that the parent component is destroyed and the plugin does not see this.$el ...

Thank you for answer
