### ISSUE TITLE
live Demo code

### ISSUE THREAD

**Issue by pouriaghadiri** [molvqingtai/vue-scroll-loader#6]
hey.. i want to use vue-scroll-loader but i cant understand how it works with api can you give me some example with live demo code?

**Comment by molvqingtai** [comment]
> hey.. i want to use vue-scroll-loader but i cant understand how it works with api can you give me some example with live demo code?

This is a simple demo.
https://github.com/molvqingtai/vue-scroll-loader/blob/master/demo.html
